### ISSUE TITLE
2024 Summer Checklist

### ISSUE THREAD

**Issue by PaarasPurohit** [PaarasPurohit/blue-owl-tutoring-site#1]
# To-Do List:

- [x] Make website
- [x] Publish website on GitHub domain
- [ ] Debug website
- [ ] Implement GitHub Pages with External Domain video into site
> - [ ] Alternative: Debug external domain issues with ChatGPT
- [ ] Finish site with ```.org``` domain.

# Procedure

Every week, the following shall be reported:

- Work done for the week
- Whether or not the site is finished
- What needs to be done
- Errors that need additional support
